import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://m.media-amazon.com/images/I/71yzxvSfsCL._SX425_.jpg",
    title: "CeraVe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "50",
    company: "Cerave",
    color: "white",
    category: "Personal Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/81MJhRednWL._AC_SX569_.jpg",
    title: "Aveeno",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Aveeno",
    color: "red",
    category: "BabyCare",
  },

  {
    img: "https://m.media-amazon.com/images/I/81qgrrGf4uL._AC_SX569_.jpg",
    title: "Sanitary Pads",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$10,00",
    newPrice: "5",
    company: "Always",
    color: "green",
    category: "Women Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/61RJqWVnMIS._SX679_.jpg",
    title: "Dove Body Wash Variety",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$80,00",
    newPrice: "70",
    company: "Dove",
    color: "black",
    category: "Personal Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/71V8bIhJEBL._SX425_.jpg",
    title: "Eye Cream",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Light Yes",
    color: "green",
    category: "Persinal Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/41HGEsYBgiL._AC_SY445_.jpg",
    title: "Cleanse Aromatherapy Room and Linen Spray",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "50",
    company: "Aromatherapy",
    color: "black",
    category: "Home Essentials",
  },

  {
    img: "https://m.media-amazon.com/images/I/413ySRKwzHL._AC_.jpg",
    title: "Cerelac",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$50,00",
    newPrice: "30",
    company: "Cerelac",
    color: "white",
    category: "BabyCare",
  },

  {
    img: "https://m.media-amazon.com/images/I/61SscAO2OnL._AC_SX569_.jpg",
    title: "Portable Heating Pad",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "LTD",
    color: "green",
    category: "Health Concerns",
  },

  {
    img: "https://m.media-amazon.com/images/I/41lqqEZtvoL._SX300_SY300_QL70_FMwebp_.jpg",
    title: "Mouthwash",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$80,00",
    newPrice: "10",
    company: "LTD",
    color: "blue",
    category: "Health Concerns",
  },

  {
    img: "https://m.media-amazon.com/images/I/612lE8N1ZzL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    title: "VWash",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$10,00",
    newPrice: "7",
    company: "LTD",
    color: "green",
    category: "Women Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/71QIHmctpxL._AC_SX569_.jpg",
    title: "Pregnancy Test, ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "34",
    company: "Clear blue LTD",
    color: "red",
    category: "Women Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/61wZJwKmEdL._SX466_.jpg",
    title: "Thermometer",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Therm LTD",
    color: "black",
    category: "Health Device",
  },
  {
    img: "https://m.media-amazon.com/images/I/81etDMKy+QL._AC_SX569_.jpg",
    title: "Knee Brace for Adults,",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Brace ltd",
    color: "white",
    category: "Health Concerns",
  },
  {
    img: "https://m.media-amazon.com/images/I/71nFLfKsOCL._AC_SY606_.jpg",
    title: " Ibuprofen",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$10,00",
    newPrice: "2",
    company: "Hospital",
    color: "black",
    category: "Health Concerns",
  },

  {
    img: "https://m.media-amazon.com/images/I/518M+1fmEFL._SY300_SX300_.jpg",
    title: " Hand Sanitizer",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Gel ltd",
    color: "green",
    category: "Personal Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/7195acRH0dL._AC_SX569_PIbundle-2,TopRight,0,0_SH20_.jpg",
    title: "Liver Care Package Liver Reboot ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Reboot ltd",
    color: "red",
    category: "Health Concerns",
  },
  {
    img: "https://m.media-amazon.com/images/I/81a5J1x2RXL._SX679_.jpg",
    title: "Mentos",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Sugarfree",
    color: "white",
    category: "Personal Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/91vcFday-KL._SX679_.jpg",
    title: "Green Tea",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$200,00",
    newPrice: "100",
    company: "Tea",
    color: "blue",
    category: "Personal Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/61L4gHzrFSL._AC_SX569_.jpg",
    title: "Vaginal Contraceptive",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "ctg ltd",
    color: "black",
    category: "Personal Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/61LBIMPwb5L._SX425_.jpg",
    title: "Cetaphil Baby Wash & Shampoo ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "50",
    company: "Vnb ltd",
    color: "black",
    category: "BabyCare",
  },
  {
    img: "https://m.media-amazon.com/images/I/71tw0liPhyL._SX425_.jpg",
    title: "Bio-Oil Skincare",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "uhg ltd",
    color: "black",
    category: "Personal Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/71MCn-0vDuL._AC_SX569_.jpg",
    title: "SKYN Original Condoms",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$14,00",
    newPrice: "15",
    company: "Nhk ltd",
    color: "red",
    category: "Personal Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/61Gk88XEmxS._SX466_.jpg",
    title: "Face Mask ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "YESS ltd",
    color: "red",
    category: "Personal Care",
  },

  {
    img: "https://m.media-amazon.com/images/I/71Md-W5PL9L._SX425_.jpg",
    title: "Whitening Toothpaste",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "tooth ltd",
    color: "black",
    category: "Personal Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/613loN6eegL._AC_SY606_.jpg",
    title: "Vitamin E 400 IU",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "IU Ltd",
    color: "black",
    category: "Health Concerns",
  },
  {
    img: "https://m.media-amazon.com/images/I/81rv8Bir6kL._AC_SY606_.jpg",
    title: "Organic Ear Oil",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Ear Oil ltd",
    color: "white",
    category: "Health Concerns",
  },
  {
    img: "https://m.media-amazon.com/images/I/61JYx6kMRVL._SY606_.jpg",
    title: "Labello",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$60,00",
    newPrice: "50",
    company: "Labello",
    color: "black",
    category: "Personal Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/51EDGMgG4iL._AC_SX569_.jpg",
    title: "Blood Pressure Monitor",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "500",
    company: "Monitor",
    color: "black",
    category: "Health Device",
  },
  {
    img: "https://m.media-amazon.com/images/I/71lh1SJzO6L._AC_SX679_.jpg",
    title: " AHCC Immune Support and Resveratrol",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$200,00",
    newPrice: "50",
    company: "AHCC",
    color: "black",
    category: "Health Concerns",
  },
  {
    img: "https://m.media-amazon.com/images/I/51fewzTfp1L._SX425_.jpg",
    title: "Kids Perfume",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "500",
    company: "perfume",
    color: "black",
    category: "BabyCare",
  },
  {
    img: "https://m.media-amazon.com/images/I/71dVYro6OwL._AC_SX679_.jpg",
    title: "Choice Kids Water Bottle",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "20",
    company: "Choice Kids Water Bottle",
    color: "black",
    category: "BabyCare",
  },
  {
    img: "https://m.media-amazon.com/images/I/81KGoUnUEWL._AC_SX569_PIbundle-336,TopRight,0,0_SH20_.jpg",
    title: "Pampers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$300,00",
    newPrice: "500",
    company: "Monitor",
    color: "black",
    category: "BabyCare",
  },
  {
    img: "https://m.media-amazon.com/images/I/618f5Y8ZGVL._AC_SX569_.jpg",
    title: "Asphyxiation Rescue Device",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "500",
    company: "Monitor",
    color: "black",
    category: "Health Device",
  },
  {
    img: "https://m.media-amazon.com/images/I/61MbKC-N1xL._AC_SX569_.jpg",
    title: "Underwear for Women",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "26",
    company: "Monitor",
    color: "black",
    category: "Women Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/81Yd+oqT9fL._SX425_.jpg",
    title: "Body Care Set",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "19",
    company: "Monitor",
    color: "black",
    category: "Women Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/81O1EZg08FL._AC_SX466_PIbundle-60,TopRight,0,0_SH20_.jpg",
    title: "Vitabiotics - Pregnacare",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "600",
    company: "Monitor",
    color: "black",
    category: "Health Condition",
  },
  {
    img: "https://m.media-amazon.com/images/I/51hS0z8B7uL._AC_SX679_.jpg",
    title: "Arm & Hammer Deodorizer Odor Busterz",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$300,00",
    newPrice: "500",
    company: "Monitor",
    color: "black",
    category: "Home Essentials",
  },
  {
    img: "https://m.media-amazon.com/images/I/51qtGP3-BJL._SX425_.jpg",
    title: " Original Shave Cream",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$200,00",
    newPrice: "55",
    company: "Monitor",
    color: "black",
    category: "Women Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/51Shc5iV7NL._SX300_SY300_QL70_FMwebp_.jpg",
    title: "Butter Balm for Stretch Marks",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "500",
    company: "Always",
    color: "green",
    category: "Women Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/51YJJxzP2nL._SY450_.jpg",
    title: "Cactus Juice",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "50",
    company: "Always",
    color: "green",
    category: "Personal Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/41RQ2KijbeL._SX300_SY300_QL70_FMwebp_.jpg",
    title: "Sun Screen",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$300,00",
    newPrice: "100",
    company: "Always",
    color: "green",
    category: "Personal Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/41yRRW1anXL._SX300_SY300_QL70_FMwebp_.jpg",
    title: "Itching/Dry Skin (11)",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "600",
    company: "Always",
    color: "green",
    category: "Women Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/71mOw94qWML._AC_SX569_.jpg",
    title: "Iron Supplement/Anaemia",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "200",
    company: "Always",
    color: "green",
    category: "Health Concerns",
  },
  {
    img: "https://m.media-amazon.com/images/I/712ja5Y2PaS.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    title: "allergies medicine for adults",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1000,00",
    newPrice: "500",
    company: "Always",
    color: "green",
    category: "Health Concerns",
  },
  {
    img: "https://m.media-amazon.com/images/I/41R2daBe-+L._SY300_SX300_.jpg",
    title: "CeraVe SA Cleanser",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "700",
    company: "Always",
    color: "green",
    category: "Personal Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/711LHZceGhL._SX425_.jpg",
    title: "Wipes with Pink Grapefruit",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1000,00",
    newPrice: "200",
    company: "Always",
    color: "green",
    category: "Women Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/41+UeKK64pL._SY300_SX300_.jpg",
    title: "Neutrogena Oil-Free Pink Grapefruit",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "200",
    company: "Always",
    color: "green",
    category: "Women Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/71HibeoeybL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    title: "Lubricant Eye Ointment",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$400,00",
    newPrice: "200",
    company: "Always",
    color: "green",
    category: "Health Concerns",
  },
  {
    img: "https://m.media-amazon.com/images/I/41OSHbl-aNL._SX300_SY300_QL70_FMwebp_.jpg",
    title: "Baby Wrap Carrier Air-Mesh",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$500,00",
    newPrice: "100",
    company: "Always",
    color: "green",
    category: "BabyCare",
  },
  {
    img: "https://m.media-amazon.com/images/I/31sVEDEQybL._SY445_SX342_QL70_FMwebp_.jpg",
    title: "Release Walker, Adult, Silver, Medical Supplies",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "800",
    company: "Always",
    color: "green",
    category: "Health Device",
  },
  {
    img: "https://m.media-amazon.com/images/I/81QXtsY8eQL._AC_SY879_.jpg",
    title: "Speed EARDOC Pro",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "900",
    company: "Always",
    color: "green",
    category: "Health Device",
  },
  {
    img: "https://m.media-amazon.com/images/I/41T7COnzJRL._SY445_SX342_QL70_FMwebp_.jpg",
    title: "Smart Back Support",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "500",
    company: "Always",
    color: "green",
    category: "Health Device",
  },
  {
    img: "https://m.media-amazon.com/images/I/41O9rvt9Y9L._SX300_SY300_QL70_FMwebp_.jpg",
    title: "Electric Toothbrush",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$200,00",
    newPrice: "500",
    company: "Always",
    color: "green",
    category: "Health Device",
  },
  {
    img: "https://m.media-amazon.com/images/I/41-1eko2vwL._SY445_SX342_QL70_FMwebp_.jpg",
    title: "Blood Pressure Cuff Set",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1000,00",
    newPrice: "900",
    company: "Always",
    color: "green",
    category: "Health Device",
  },
  {
    img: "https://m.media-amazon.com/images/I/61lsVLRSWcL._AC_SX569_.jpg",
    title: "Electric Ear Dryer",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1000,00",
    newPrice: "44",
    company: "Always",
    color: "green",
    category: "Health Device",
  },
  {
    img: "https://m.media-amazon.com/images/I/611TGa9R3VL._AC_SX569_.jpg",
    title: "Mens Arginmax",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "50",
    company: "Always",
    color: "green",
    category: "Health Condition",
  },
  {
    img: "https://m.media-amazon.com/images/I/61zvK+8LLEL._AC_SX569_.jpg",
    title: "GNC Menopause",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "44",
    company: "Always",
    color: "green",
    category: "Health Condition",
  },
  {
    img: "https://m.media-amazon.com/images/I/51myyDX9UdL._AC_SX569_PIbundle-2,TopRight,0,0_SH20_.jpg",
    title: "Plan B One-Step Emergency Contraceptive",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$200,00",
    newPrice: "23",
    company: "Always",
    color: "green",
    category: "Health Condition",
  },
  {
    img: "https://m.media-amazon.com/images/I/71Zp9KuAJsL._SX425_.jpg",
    title: "NIVEA Vanilla and Almond Oil",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$200,00",
    newPrice: "50",
    company: "Always",
    color: "green",
    category: "Personal Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/41H-GaQJAxL._SX679_.jpg",
    title: "Johnson's Baby Powder",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$200,00",
    newPrice: "100",
    company: "Always",
    color: "green",
    category: "BabyCare",
  },
  {
    img: "https://m.media-amazon.com/images/I/71ZTLzz2kOL._AC_SX569_.jpg",
    title: "Clinically Tested Baby Nasal Aspirator",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "600",
    company: "Always",
    color: "green",
    category: "BabyCare",
  },
  {
    img: "https://m.media-amazon.com/images/I/5174jRLxqSL._SX300_SY300_QL70_FMwebp_.jpg",
    title: "Baby Essentials Care Kit",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "200",
    company: "Always",
    color: "green",
    category: "BabyCare",
  },
  {
    img: "https://m.media-amazon.com/images/I/51Y1QHlvQyL._SX425_.jpg",
    title: " Breast Pump & Breast Milk Storage Bags",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "50",
    company: "Always",
    color: "green",
    category: "BabyCare",
  },
  {
    img: "https://m.media-amazon.com/images/I/61FK9QydwPL._AC_SX569_.jpg",
    title: " Infant Formula Nutrition",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "500",
    company: "Always",
    color: "green",
    category: "BabyCare",
  },
  {
    img: "https://m.media-amazon.com/images/I/71dl5k4HVEL._AC_SX522_.jpg",
    title: "green sprouts Stay-dry Milk Catcher Bibs",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$300,00",
    newPrice: "57",
    company: "Always",
    color: "green",
    category: "BabyCare",
  },
  {
    img: "https://m.media-amazon.com/images/I/81h2tpMsQwL._AC_SX569_PIbundle-6,TopRight,0,0_SH20_.jpg",
    title: "Room Spray",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "500",
    company: "Always",
    color: "green",
    category: "Home Essentials",
  },
  {
    img: "https://m.media-amazon.com/images/I/71N+91HhT6L._AC_SY300_SX300_.jpg",
    title: "Mosquito Killer Lamp",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "900",
    company: "Always",
    color: "green",
    category: "Home Essentials",
  },
  {
    img: "https://m.media-amazon.com/images/I/41p+1eW+Q5L._SX425_.jpg",
    title: "Net Tent",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "500",
    company: "Always",
    color: "green",
    category: "BabyCare",
  },
  {
    img: "https://m.media-amazon.com/images/I/71ZcTdb2WXL._AC_SX569_PIbundle-100,TopRight,0,0_SH20_.jpg",
    title: "Heel Diarrhea 100 Tb",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "500",
    company: "Always",
    color: "green",
    category: "Health Concerns",
  },
  {
    img: "https://m.media-amazon.com/images/I/61pScZ5iiqL._AC_SX569_.jpg",
    title: "Anxie-T - Stress Relief Supplement",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "20",
    company: "Always",
    color: "green",
    category: "Health Concerns",
  },
  {
    img: "https://m.media-amazon.com/images/I/71h19mgrz2L.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    title: "Yeast Infection Treatment",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "80",
    company: "Always",
    color: "green",
    category: "Women Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/81+Pl2m8LBL._AC_SX569_PIbundle-2,TopRight,0,0_SH20_.jpg",
    title: "Cold, Flu, and Congestion Medicine",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "25",
    company: "Always",
    color: "green",
    category: "Health Concerns",
  },
  {
    img: "https://m.media-amazon.com/images/I/71edrv4VWAL._SX425_.jpg",
    title: "Kids Cold Medicine and Mucus Relief",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$300,00",
    newPrice: "100",
    company: "Always",
    color: "green",
    category: "BabyCare",
  },
  {
    img: "https://m.media-amazon.com/images/I/71l1Q1W8bRL._AC_SX569_.jpg",
    title: " First Aid Blood Stopper",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "500",
    company: "Always",
    color: "green",
    category: "Health Concerns",
  },
  {
    img: "https://m.media-amazon.com/images/I/A1-CR1AF+-L._SX466_.jpg",
    title: "Abdominal Binder for Women",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "800",
    company: "Always",
    color: "green",
    category: "Health Concerns",
  },
  {
    img: "https://m.media-amazon.com/images/I/81uWEcYQQQS._AC_SX522_.jpg",
    title: "Disposable Gloves",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "80",
    company: "Always",
    color: "green",
    category: "Personal Care",
  },
  {
    img: "https://m.media-amazon.com/images/I/71WviUSzGqL._SX466_.jpg",
    title: "Glucometers & Test Strips",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "500",
    company: "Always",
    color: "green",
    category: "Health Device",
  },
  {
    img: "https://m.media-amazon.com/images/I/81lNwxmNgoL._SX466_.jpg",
    title: "weighing machine for body weight",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1000,00",
    newPrice: "800",
    company: "Always",
    color: "green",
    category: "Health Device",
  },
  {
    img: "https://m.media-amazon.com/images/I/91z1JKz9mYL._AC_SX569_.jpg",
    title: "clavicle support brace",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$200,00",
    newPrice: "100",
    company: "Always",
    color: "green",
    category: "Health Device",
  },
  {
    img: "https://m.media-amazon.com/images/I/71fPm4QyFuL._AC_SX569_.jpg",
    title: "Neck Stretcher for Neck Pain Relief",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100,00",
    newPrice: "800",
    company: "Always",
    color: "green",
    category: "Health Device",
  },
];

export default data;